<?php
/**
 * @file
 * Code for the UAQS Alphabetical List feature.
 */

include_once 'uaqs_alphabetical_list.features.inc';

/**
 * Implements hook_theme_registry_alter().
 */
function uaqs_alphabetical_list_theme_registry_alter(&$theme_registry) {
  // Find all .tpl.php files in this module's folder recursively.
  $module_path = drupal_get_path('module', 'uaqs_alphabetical_list');
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);

  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}

function uaqs_alphabetical_list_preprocess_views_view(&$variables) {
  if ($variables['view']->name == 'uaqs_alphabetical_listing') {
    $js['#attached']['js'][] = array(
      'data' => drupal_get_path('module', 'uaqs_alphabetical_list') . '/js/uaqs_alphabetical_list.js',
      'type' => 'file',
      'scope' => 'footer',
      'group' => JS_THEME,
    );
    drupal_render($js);
  }
}
