<?php
/**
 * @file
 * Code for the UAQS Person View feature.
 */

include_once 'uaqs_person_view.features.inc';

/**
 * Implements hook_views_default_views_alter().
 *
 * Enables content caching for the uaqs_person_directory view when the
 * views_content_cache module is available.
 */
function uaqs_person_view_views_default_views_alter(&$views) {
  if (module_exists('views_content_cache')) {
    if (isset($views['uaqs_person_directory'])) {
      $node_type_keys = array();
      foreach (node_type_get_names() as $type => $name) {
        if ($type == 'uaqs_person') {
          $node_type_keys[$type] = $type;
        }
        else {
          $node_type_keys[$type] = 0;
        }
      }

      $views['uaqs_person_directory']->display['default']->display_options['cache']['type'] = 'views_content_cache';
      $views['uaqs_person_directory']->display['default']->display_options['cache']['results_min_lifespan'] = '-1';
      $views['uaqs_person_directory']->display['default']->display_options['cache']['results_max_lifespan'] = '21600';
      $views['uaqs_person_directory']->display['default']->display_options['cache']['output_min_lifespan'] = '-1';
      $views['uaqs_person_directory']->display['default']->display_options['cache']['output_max_lifespan'] = '21600';
      $views['uaqs_person_directory']->display['default']->display_options['cache']['keys'] = array(
        'node' => $node_type_keys,
        'node_only' => array(
          'node_changed' => 'node_changed',
        ),
      );

      if (module_exists('draggableviews')) {
        $draggableviews_keys = array();
        foreach (_draggableviews_get_views_options() as $view_id => $view_title) {
          if ($view_id == 'uaqs_reorder_people:page') {
            $draggableviews_keys[$view_id] = $view_id;
          }
          else {
            $draggableviews_keys[$view_id] = 0;
          }
        }
        $views['uaqs_person_directory']->display['default']->display_options['cache']['keys']['draggableviews'] = $draggableviews_keys;
      }
    }
  }
}
