<?php
/**
 * @file
 * Code for the UAQS Navigation feature.
 */

/**
 * Implements hook_migrate_api().
 *
 * @todo Investigate why setting the 'import_root' argument doesn't work at the
 *   group level. Should work. https://www.drupal.org/node/1824884
 */
function uaqs_navigation_global_footer_migrate_api() {
  $import_root = drupal_get_path('module', 'uaqs_navigation_global_footer') . '/import';

  $api = array(
    'api' => 2,
    'groups' => array(
      'uaqs_navigation' => array(
        'title' => t('UAQS Navigation'),
// This should work...
//        'import_root' => $import_root,
      ),
    ),
    'migrations' => array(
      'UaqsNavigationGlobalFooter' => array(
        'class_name' => 'UaqsNavigationGlobalFooterMigration',
        'group_name' => 'uaqs_navigation',
        'import_root' => $import_root,
      ),
      'UaqsNavigationGlobalFooterBean' => array(
        'class_name' => 'UaqsNavigationGlobalFooterBeanMigration',
        'group_name' => 'uaqs_navigation',
        'dependencies' => array(
            'UaqsNavigationGlobalFooter',
        ),
        'import_root' => $import_root,
      ),
    ),
  );
  return $api;
}

/**
 * Implements hook_theme_registry_alter().
 */
function uaqs_navigation_global_footer_theme_registry_alter(&$theme_registry) {
  // Find all .tpl.php files in this module's folder recursively.
  $module_path = drupal_get_path('module', 'uaqs_navigation_global_footer');
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);

  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}
