<?php
/**
 * @file
 * Code for the UAQS Navigation - Select Menu feature.
 */

include_once 'uaqs_navigation_select_menu.features.inc';

/**
 * Implements hook_bean_types_api_info().
 * This function allows the bean to show up in the UI when paired with the
 * 'abstract' => FALSE, value in hook_bean_types()
 */
function uaqs_navigation_select_menu_bean_types_api_info() {
  return array('api' => 4);
}

/**
 * Implements hook_preprocess_block().
 * Override or insert variables into the block template.
 */
function uaqs_navigation_select_menu_preprocess_block(&$variables) {
  if (isset($variables['elements']['#theme']) && ($variables['elements']['#theme'] == 'uaqs_navigation_select_menu')) {
    if (isset($variables['elements']['#wrapper_classes'])) {
      $variables['classes_array'] = array_merge($variables['classes_array'], $variables['elements']['#wrapper_classes']);
    }
  }

  if ($variables['block_html_id'] == 'block-bean-uaqs-audience-select') {
    $variables['attributes_array']['aria-label'] = 'select menu';
  }
}

/**
 * Implements hook_bean_types().
 */
function uaqs_navigation_select_menu_bean_types() {
  $plugins = array();
  $plugin_path = drupal_get_path('module', 'uaqs_navigation_select_menu') . '/plugins';
  $plugins['uaqs_select_menu'] = array(
    'label' => t('Select Menu'),
    'description' => t('Add menu block that allows selecting menu items from a select element'),
    'abstract' => FALSE,
    'handler' => array(
      'class' => 'UaqsSelectMenuBean',
      'parent' => 'bean',
      'path' => $plugin_path,
      'file' => 'UaqsSelectMenuBean.class.php'
    ),
  );
  return $plugins;
}

/**
 * Implements hook_theme().
 */
function uaqs_navigation_select_menu_theme() {
  return array(
    'uaqs_navigation_select_menu' => array(
      'template' => 'templates/uaqs_navigation_select_menu',
      'variables' => array(
        'menu_items' => array(),
        'select_id' => NULL,
        'preform_text' => NULL,
        'preform_text_sr_only' => NULL,
        'button_text' => NULL,
        'button_text_sr_only' => NULL,
      ),
    ),
  );
}
