<?php
/**
 * @file
 * Make file entities editable inline within other entity forms.
 */

define('FILE_ENTITY_INLINE_ALL', '1');
define('FILE_ENTITY_INLINE_SOME', '2');
define('FILE_ENTITY_INLINE_NONE', '0');

/**
 * Implements hook_field_widget_form_alter().
 */
function file_entity_inline_field_widget_form_alter(&$element, &$form_state, $context) {
  $instance = $context['instance'];
  if (array_key_exists($instance['widget']['type'], file_entity_inline_widgets())) {
    foreach (element_children($element) as $key) {
      $element[$key] = file_entity_inline_file_field_widget_form_alter($element[$key], $form_state, $instance);
    }
  }
}

/**
 * Adds the additional file entity fields to the widget.
 */
function file_entity_inline_file_field_widget_form_alter($element, &$form_state, $instance) {
  // We need to add #process callback due to 2 reasons:
  // 1. Entire $form is not available in hook_field_widget_form_alter().
  // 2. Walkaround on Drupal core bug. We need to change how file widget submit
  //    callback searches for the submitted values.
  //    See: http://drupal.org/node/1468686
  $element['#process'] = array_merge($element['#process'], array('file_entity_inline_field_widget_process'));

  // Only act on entity forms, and when a file has been uploaded.
  $file = (object) $element['#default_value'];
  if (empty($file->fid) || !isset($element['#entity_type']) || !isset($element['#field_name'])) {
    return $element;
  }

  // Sorry, no recursive inline-editing of files. ;)
  if ($element['#entity_type'] === 'file') {
    return $element;
  }

  // Load the settings for this field.
  $widget_settings = $instance['widget']['settings'];

  // Bail out if inline file entities are not enabled on this field.
  if (isset($widget_settings['file_entity_inline']) && $widget_settings['file_entity_inline'] == FILE_ENTITY_INLINE_NONE) {
    return $element;
  }

  // The File Entity module adds some extra requirements that will not be added
  // by the Plupload module, so manually append all values from the file_managed
  // table to the $file object.
  if (!isset($file->type)) {
    // Fill out the file object so that it has all of the expected data.
    $query = db_query('SELECT * FROM {file_managed} WHERE fid = :fid', array(
      ':fid' => $file->fid,
    ));
    $results = $query->fetchAssoc();
    if (!empty($results)) {
      foreach ($results as $key => $val) {
        $file->{$key} = $val;
      }
    }
  }

  // Add the entity form for the file.
  $element['entity'] = array(
    '#weight' => 10,
    '#parents' => array('files', $file->fid),
  );
  field_attach_form('file', $file, $element['entity'], $form_state, $element['#language']);

  // Reduce the display of fields if only display specific fields.
  if (isset($widget_settings['file_entity_inline']) && $widget_settings['file_entity_inline'] == FILE_ENTITY_INLINE_SOME) {
    $disabled_fields = array_diff(element_children($element['entity']), $widget_settings['file_entity_inline_fields']);
    foreach ($disabled_fields as $form_key) {
      $element['entity'][$form_key]['#access'] = FALSE;
    }
  }

  return $element;
}

/**
 * An element #process callback for the file field widget.
 */
function file_entity_inline_field_widget_process($element, &$form_state, &$form) {
  // Walkaround on Drupal core bug.
  // See: http://drupal.org/node/1468686
  foreach (array('upload_button', 'remove_button') as $key) {
    foreach ($element[$key]['#submit'] as $delta => $submit) {
      if ($submit == 'file_field_widget_submit') {
        $element[$key]['#submit'][$delta] = 'file_entity_inline_field_widget_submit';
      }
    }
  }

  // Only act on entity forms, and when a file has been uploaded.
  if (empty($element['fid']['#value']) || !isset($element['#entity_type']) || !isset($element['#field_name'])) {
    return $element;
  }

  // Sorry, no recursive inline-editing of files. ;)
  if ($element['#entity_type'] === 'file') {
    return $element;
  }

  // Add a submit handler to the entire form to handle saving of values.
  if (array_search('file_entity_inline_submit', $form['#submit']) === FALSE) {
    $form['#submit'][] = 'file_entity_inline_submit';
  }

  return $element;
}
/**
 * Fixed file_field_widget_submit(). See: http://drupal.org/node/1468686
 *
 * @see file_entity_inline_field_widget_process()
 * @see file_field_widget_submit()
 */
function file_entity_inline_field_widget_submit($form, &$form_state) {
  // During the form rebuild, file_field_widget_form() will create field item
  // widget elements using re-indexed deltas, so clear out $form_state['input']
  // to avoid a mismatch between old and new deltas. The rebuilt elements will
  // have #default_value set appropriately for the current state of the field,
  // so nothing is lost in doing this.
  $parents = array_slice($form_state['triggering_element']['#parents'], 0, -2);
  drupal_array_set_nested_value($form_state['input'], $parents, NULL);

  $button = $form_state['triggering_element'];

  // Go one level up in the form, to the widgets container.
  $element = drupal_array_get_nested_value($form, array_slice($button['#array_parents'], 0, -1));
  $field_name = $element['#field_name'];
  $langcode = $element['#language'];
  $parents = $element['#field_parents'];

  $submitted_values = drupal_array_get_nested_value($form_state['values'], array_slice($button['#parents'], 0, -2));
  foreach ($submitted_values as $delta => $submitted_value) {
    if (!$submitted_value['fid']) {
      unset($submitted_values[$delta]);
    }
  }

  // Re-index deltas after removing empty items.
  $submitted_values = array_values($submitted_values);

  // Update form_state values.
  drupal_array_set_nested_value($form_state['values'], array_slice($button['#parents'], 0, -2), $submitted_values);

  // Update items.
  $field_state = field_form_get_state($parents, $field_name, $langcode, $form_state);
  $field_state['items'] = $submitted_values;
  field_form_set_state($parents, $field_name, $langcode, $form_state, $field_state);
}

/**
 * An element #element_validate callback for the file entity.
 *
 * Saves the file entity field values.
 */
function file_entity_inline_submit($form, &$form_state) {
  if (!isset($form_state['values']['files'])) {
    return;
  }

  // Save any file entities on the page.
  foreach ($form_state['values']['files'] as $fid => $file_values) {
    $file = file_load($fid);
    $file_form_state = array(
      'values' => $file_values,
    );
    field_attach_submit('file', $file, $form, $file_form_state);
    file_save($file);
  }
}


/**
 * Implements hook_form_alter().
 */
function file_entity_inline_form_field_ui_field_edit_form_alter(&$form, $form_state) {
  $instance = $form['#instance'];

  // Check that we're not on a file entity, and this widget is supported.
  if ($instance['entity_type'] !== 'file' && array_key_exists($instance['widget']['type'], file_entity_inline_widgets())) {
    $field = $form['#field'];
    if (empty($form['instance']['settings'])) {
      $form['instance']['settings'] = array();
    }
    $form['instance']['settings'] += file_entity_inline_field_widget_settings_form($field, $instance);
  }
}

/**
 * Implements hook_field_widget_info_alter().
 *
 * A list of settings needed by File Entity Inline module on widgets.
 */
function file_entity_inline_field_widget_info_alter(&$info) {
  $settings = array(
    'file_entity_inline' => 1,
    'file_entity_inline_fields' => array(),
  );

  foreach (file_entity_inline_widgets() as $widget_type => $widget) {
    if (isset($info[$widget_type]['settings'])) {
      $info[$widget_type]['settings'] += $settings;
    }
  }
}

/**
 * Configuration form for editing File Entity Inline for a field instance.
 */
function file_entity_inline_field_widget_settings_form($field, $instance) {
  $widget = $instance['widget'];
  $settings = $widget['settings'];

  $form['file_entity_inline'] = array(
    '#type' => 'fieldset',
    '#title' => t('Inline fields'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#description' => t('These options allow extended file properties to be edited inline after a file has been uploaded into this field. The fields displayed will depend upon the type of file uploaded. Setting or changing a value in these fields will affect the file everywhere throughout the site. More fields may be added in the <a href="!file-types">File types configuration</a>', array('!file-types' => url('admin/structure/file-types'))),
    '#weight' => 30,
    '#parents' => array('instance', 'widget', 'settings'),
  );

  $form['file_entity_inline']['file_entity_inline'] = array(
    '#type' => 'select',
    '#title' => t('Inline fields'),
    '#options' => array(
      FILE_ENTITY_INLINE_ALL => t('All available fields'),
      FILE_ENTITY_INLINE_SOME => t('Only specific fields'),
      FILE_ENTITY_INLINE_NONE => t('None (disabled)'),
    ),
    '#default_value' => isset($settings['file_entity_inline']) ? $settings['file_entity_inline'] : 1,
    '#weight' => -9,
  );

  $options = array();
  $option_occurances = array();
  $instance_info = field_info_instances('file');
  $bundle_info = field_info_bundles('file');
  foreach ($instance_info as $bundle_name => $bundle_fields) {
    foreach ($bundle_fields as $field_name => $field_instance) {
      $options[$field_name] = $field_instance['label'];
      $option_occurances[$field_name][] = $bundle_info[$bundle_name]['label'];
    }
  }

  // Add bundle information to each field name.
  foreach ($options as $field_name => $field_label) {
    $options[$field_name] .= ' (' . implode(',', $option_occurances[$field_name]) . ')';
  }

  $form['file_entity_inline']['file_entity_inline_fields'] = array(
    '#title' => t('Included inline fields'),
    '#type' => 'checkboxes',
    '#options' => $options,
    '#default_value' => isset($settings['file_entity_inline_fields']) ? $settings['file_entity_inline_fields'] : array(),
    '#weight' => 0,
    '#states' => array(
      'visible' => array(
        'select[name="instance[widget][settings][file_entity_inline]"]' => array('value' => 2),
      ),
    ),
    '#element_validate' => array('file_entity_inline_fields_validate'),
  );

  return $form;
}

/**
 * Form #element_validate callback. Return only values on checked checkboxes.
 */
function file_entity_inline_fields_validate($element, &$form_state) {
  $value = array_values(array_filter($element['#value']));
  form_set_value($element, $value, $form_state);
}

/**
 * Get a list of all supported field widgets.
 */
function file_entity_inline_widgets($reset = FALSE) {
  static $widgets;

  if (!isset($widgets) || $reset) {
    $widgets = array();
    foreach (module_implements('file_entity_inline_widgets') as $module) {
      $module_widgets = module_invoke($module, 'file_entity_inline_widgets');
      foreach ($module_widgets as $type => $widget) {
        $module_widgets[$type]['type'] = $type;
        $module_widgets[$type]['module'] = $module;
      }
      $widgets = array_merge($widgets, $module_widgets);
    }
    drupal_alter('file_entity_inline_widgets', $widgets);
  }

  return $widgets;
}

/**
 * Implements hook_file_entity_inline_widgets().
 */
function file_entity_inline_file_entity_inline_widgets() {
  $widgets = array();
  $widgets['file_generic'] = array(
    'element_type' => 'managed_file',
  );
  $widgets['image_image'] = array(
    'element_type' => 'managed_file',
  );
  return $widgets;
}

