<?php
/**
 * @file
 * ua_google_tag.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function ua_google_tag_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'google_tag_compact_tag';
  $strongarm->value = 1;
  $export['google_tag_compact_tag'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'google_tag_container_id';
  $strongarm->value = 'GTM-ML2BZB';
  $export['google_tag_container_id'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'google_tag_path_list';
  $strongarm->value = 'admin*
batch*
node/add/*
node/*/edit
block/add/*
block/*/edit
user/*/edit
file/add
file/*/edit
taxonomy/term/*/edit';
  $export['google_tag_path_list'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'google_tag_path_toggle';
  $strongarm->value = 'exclude listed';
  $export['google_tag_path_toggle'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'google_tag_role_list';
  $strongarm->value = array(
    'anonymous user' => 'anonymous user',
    'authenticated user' => 0,
    'administrator' => 0,
  );
  $export['google_tag_role_list'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'google_tag_role_toggle';
  $strongarm->value = 'include listed';
  $export['google_tag_role_toggle'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'google_tag_status_list';
  $strongarm->value = '403 Forbidden
404 Not Found';
  $export['google_tag_status_list'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'google_tag_status_toggle';
  $strongarm->value = 'exclude listed';
  $export['google_tag_status_toggle'] = $strongarm;

  return $export;
}
